# Generated by Django 5.2.7 on 2025-10-18 18:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('party', models.CharField(blank=True, max_length=60)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 dígitos numéricos (sem pontuação).')])),
                ('registration', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('allowed', models.BooleanField(default=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('last_voted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('cpf', 'registration')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='urna.candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='urna.voter')),
            ],
        ),
    ]
