# Generated by Django 5.2.7 on 2025-10-18 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0002_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='urna.funcionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='last_voted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(help_text='Digite apenas os 11 números do CPF.', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 dígitos numéricos (sem pontuação).')]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='re',
            field=models.CharField(help_text='Registro do funcionário.', max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
