# Generated by Django 5.2.7 on 2025-10-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urna', '0003_alter_vote_voter_funcionario_has_voted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(help_text='O CPF será salvo no formato 123.456.789-00', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='re',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
